import { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Modal from '../components/Modal';
import styles from '../styles/Home.module.scss';
import Accepted from '../components/Accepted';
import Section from '../components/Section';

export default function Home() {
	const [showModal, setShowModal] = useState(false);
	const [accept, setAccept] = useState(null);
	const handleAccept = (e) => {
		setShowModal(true);
		setAccept(true);
		console.log(e.target);
	};
	const handleDecline = (e) => {
		setShowModal(true);
		setAccept(false);
		console.log(e.target);
	};

	return (
		<div className='wrapper'>
			<div className='container'>
				<div className='container__content'>
					<Head>
						<title>James and Tinas Wedding</title>
						<meta
							name='description'
							content='Generated by create next app'
						/>
						<link rel='icon' href='/favicon.ico' />
					</Head>
					<header className={styles.header}>
						<div className={styles.header__content}>
							<p className={styles.header__logo}>
								James and Tinas Wedding
							</p>
							<nav className={styles.header__nav}>
								<ul className={styles.header__navItems}>
									<li className='header__nav-item'>
										<Link href='/covid'>
											<a>Covid</a>
										</Link>
									</li>
								</ul>
							</nav>
						</div>
					</header>
				</div>
			</div>

			<main className='wrapper'>
				<section className='container'>
					<div className='container__content'>
						<div className='container__title'>Day</div>
						<section className={styles.section}></section>
						<button onClick={handleAccept}>Accept</button>
						<button onClick={handleDecline}>Decline</button>
					</div>
				</section>
				<Section
					headerBackground='yellow'
					bodyBackground='blue'
					title='Day'
					subtitle='tetx'>
					<p>
						Lorem ipsum dolor sit amet consectetur, adipisicing
						elit. Dolores, ab!
					</p>
				</Section>
				<Section
					headerBackground='orange'
					bodyBackground='cornflowerblue'
					title='Day'
					subtitle='text'>
					<p>
						Lorem ipsum dolor sit amet consectetur, adipisicing
						elit. Dolores, ab!
					</p>
				</Section>
				<Section
					headerBackground='orange'
					bodyBackground='cornflowerblue'
					title='Day'
					subtitle='text'>
					<p>
						Lorem ipsum dolor sit amet consectetur, adipisicing
						elit. Dolores, ab!
					</p>
				</Section>
				<Section
					headerBackground='orange'
					bodyBackground='cornflowerblue'
					title='Day'
					subtitle='text'>
					<p>
						Lorem ipsum dolor sit amet consectetur, adipisicing
						elit. Dolores, ab!
					</p>
				</Section>

				<section className='container'>
					<div className='container__content'>
						<h2 className='container__title'>Night</h2>
					</div>
				</section>
			</main>
			<footer className={styles.footer}></footer>
			<Modal onClose={() => setShowModal(false)} show={showModal}>
				{accept && <Accepted />}
				{!accept && <p>You declined</p>}
			</Modal>
		</div>
	);
}
